spring.application.name=Mini_Bank_Project


server.port=8080


server.servlet.context-path=/bank


# JSP View Resolver Configuration

spring.mvc.view.prefix=/WEB-INF/bank/
spring.mvc.view.suffix=.jsp


# Oracle Database Configuration

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=Bhushan_Table
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JDBC Settings
 
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# JSP Development Settings

server.servlet.jsp.init-parameters.development=true


# Logging

logging.level.org.springframework.jdbc.core=DEBUG
logging.level.com.bhushan=DEBUG


# Disable Spring Banner (Optional)

spring.main.banner-mode=console